modLoader="javafml"
loaderVersion="[1,)"
license="Apache-2.0"

[[mods]]
modId="mineclawd"
version="${version}"
displayName="MineClawd"
description='''Bring OpenClaw into Minecraft! The Minecraft Agent that actually do things.'''
displayURL="https://github.com/Zhou-Shilin/MineClawd"
logoFile="assets/mineclawd/icon.png"

[[dependencies.mineclawd]]
modId="neoforge"
type="required"
versionRange="[1,)"
ordering="NONE"
side="BOTH"

[[dependencies.mineclawd]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
